name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm ci
        npm run build-storybook

    - name: Init new repo in dist folder and commit generated files
      run: |
        cd storybook-static
        git init
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'deploy'

  - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        # Token for the repo
        # Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Destination branch to push changes
        branch: gh-pages
        # Use force push to fully overwrite the destination branch
        force: true
        # We have to push from the folder where files were generated.
        # Same were the new repo was initialized in the previous step
        directory: ./storybook-static